### ISSUE TITLE
Revision 23 de Marzo

### ISSUE THREAD

**Issue by gera-gpz** [arvafik/p2_17100229#1]
Muy bien, solo en la serie Fibo.
Correcto: 0 , 1 , 2 , 3 , 5 , 8
Incorrecto 0 , 1 , 1 , 2 , 3 , 5 , 8

Pero el punto del ejercicio era usar JS
y varios de ustedes ya saben :+1:

**Comment by arvafik** [comment]
Se repite el segundo numero, ups!
